config/routes.rb
Lalulins::Application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  get 'tag/:tag', to: 'posts#tags', as: :tag
  get 'post/:id/', to: 'posts#post', as: :post
  get 'post/:id/:category_id', to: 'posts#post'
  get 'preview/:id/', to: 'posts#preview', as: :preview
  get 'busca/', to: 'posts#busca', as: :busca
  get 'categoria/:category_id', to: 'posts#categoria', as: :categoria
  get 'contato', to: 'home#contato', as: :contato
  post 'contato/', to: 'home#send_contato', as: :contact_forms
  get 'anuncie/', to: 'home#anuncie', as: :anuncie
  post 'anuncie/', to: 'home#send_anuncie', as: :advertise_forms
  get 'sobre', to: 'home#sobre', as: :sobre
  get 'home/index'
  get 'feed/', to: 'home#feed'

  namespace :admin do
    get 'home/index'
    resources :categories
    resources :posts
    resources :sponsors
  end

  mount Ckeditor::Engine => '/ckeditor'

  root 'home#index'

  get 'admin' => 'admin/home#index', as: :user_root

end

app/models/admin/sponsor.rb
class Admin::Sponsor < Sponsor
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_many :posts

  validates_presence_of :name, :address, :phone

  has_attached_file :logo,
                    :styles => {original: "100x100#"},
                    :default_url => "sem-foto2.png",
                    :url => "/images/sponsors/:attachment/:id_partition/:style/:filename",
                    :path => ":rails_root/public/images/sponsors/:attachment/:id_partition/:style/:filename"
end

app/controllers/admin/sponsors_controller.rb
class Admin::SponsorsController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!
  before_action :set_admin_sponsor, only: [:show, :edit, :update, :destroy]

  # GET /admin/sponsors
  # GET /admin/sponsors.json
  def index
    @admin_sponsors = Admin::Sponsor.all
  end

  # GET /admin/sponsors/1
  # GET /admin/sponsors/1.json
  def show
  end

  # GET /admin/sponsors/new
  def new
    @admin_sponsor = Admin::Sponsor.new
  end

  # GET /admin/sponsors/1/edit
  def edit
  end

  # POST /admin/sponsors
  # POST /admin/sponsors.json
  def create
    @admin_sponsor = Admin::Sponsor.new(admin_sponsor_params)

    respond_to do |format|
      if @admin_sponsor.save
        format.html { redirect_to admin_sponsors_path, notice: 'Sponsor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_sponsor }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/sponsors/1
  # PATCH/PUT /admin/sponsors/1.json
  def update
    respond_to do |format|
      if @admin_sponsor.update(admin_sponsor_params)
        format.html { redirect_to admin_sponsors_path, notice: 'Sponsor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/sponsors/1
  # DELETE /admin/sponsors/1.json
  def destroy
    @admin_sponsor.destroy
    respond_to do |format|
      format.html { redirect_to admin_sponsors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_sponsor
      @admin_sponsor = Admin::Sponsor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_sponsor_params
      params.require(:admin_sponsor).permit(:name, :address, :phone, :email, :site, :instagram, :facebook, :whatsapp, :logo)
    end
end

app/helpers/admin/sponsors_helper.rb
module Admin::SponsorsHelper
end

app/views/admin/sponsors/_form.html.erb
<%= simple_form_for @admin_sponsor, :html => {:class => 'form-horizontal'} do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.input :site, as: :url %>
    <%= f.input :instagram, as: :url %>
    <%= f.input :facebook, as: :url %>
    <%= f.input :whatsapp, label: 'WhatsApp', as: :tel %>

    <div class="control-group">
      <label class="control-label">Imagem</label>

      <div class="controls">
        <%= image_tag @admin_sponsor.logo.url(:original) %>
      </div>
    </div>
    <%= f.input :logo, as: :file %>

    <div class="form-actions">
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  admin_sponsors_path, :class => 'btn' %>
    </div>
<% end %>

app/views/admin/sponsors/edit.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/sponsors/index.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:logo) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th class="actions"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @admin_sponsors.each do |sponsor| %>
      <tr>
        <td><%= link_to image_tag(sponsor.logo.url(:original)), edit_admin_sponsor_path(sponsor) %></td>
        <td><%= link_to sponsor.name, edit_admin_sponsor_path(sponsor) %></td>
        <td><%= sponsor.phone %></td>
        <td><%= sponsor.email %></td>
        <td class="actions">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_sponsor_path(sponsor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_sponsor_path(sponsor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_sponsor_path,
            :class => 'btn btn-primary' %>

app/views/admin/sponsors/new.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/sponsors/show.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @admin_sponsor.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @admin_sponsor.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @admin_sponsor.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @admin_sponsor.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:instagram) %>:</strong></dt>
  <dd><%= @admin_sponsor.instagram %></dd>
  <dt><strong><%= model_class.human_attribute_name(:facebook) %>:</strong></dt>
  <dd><%= @admin_sponsor.facebook %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_sponsors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_sponsor_path(@admin_sponsor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_sponsor_path(@admin_sponsor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>