config/routes.rb
Lalulins::Application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  get 'tag/:tag', to: 'posts#tags', as: :tag
  get 'post/:id/', to: 'posts#post', as: :post
  get 'post/:id/:category_id', to: 'posts#post'
  get 'preview/:id/', to: 'posts#preview', as: :preview
  get 'busca/', to: 'posts#busca', as: :busca
  get 'categoria/:category_id', to: 'posts#categoria', as: :categoria
  get 'contato', to: 'home#contato', as: :contato
  post 'contato/', to: 'home#send_contato', as: :contact_forms
  get 'anuncie/', to: 'home#anuncie', as: :anuncie
  post 'anuncie/', to: 'home#send_anuncie', as: :advertise_forms
  get 'sobre', to: 'home#sobre', as: :sobre
  get 'home/index'
  get 'feed/', to: 'home#feed'

  namespace :admin do
    get 'home/index'
    resources :categories
    resources :posts
    resources :sponsors
  end

  mount Ckeditor::Engine => '/ckeditor'

  root 'home#index'

  get 'admin' => 'admin/home#index', as: :user_root

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#" lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Admin - Lalu" %></title>
  <%= csrf_meta_tags %>

  <link rel="shortcut icon" href="http://www.lalulins.com.br/favicon.ico" type="image/x-icon" />

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<%= nav_bar :fixed => :top, :brand => "Admin", :brand_link => user_root_path, :responsive => true do %>
    <% if user_signed_in? %>
        <%= menu_group do %>
            <%= menu_divider %>
            <%= menu_item "Categorias", admin_categories_path %>
            <%= menu_item "Posts", admin_posts_path %>
            <%= menu_item "Comentários", "https://developers.facebook.com/tools/comments", target: '_blank' %>
            <%= menu_item "Anunciantes", admin_sponsors_path %>
        <% end %>
        <%= menu_group :pull => :right do %>
            <%= menu_divider %>
            <li><%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
        <% end %>
    <% end %>
<% end %>


<div id="main" class="container clear-top">
  <div class="row-fluid">
    <div class="span12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
  <!--/row-->
  <div class="push"></div>
</div>
<!-- /container -->
<footer class="footer">
  <p>&copy; Lalu Lins 2013</p>
</footer>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= yield (:title) || "" %>Lalu Lins</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= content_for?(:metatags) ? yield(:metatags) : '' %>

  <link rel="shortcut icon" href="http://www.lalulins.com.br/favicon_origin.png" type="image/png"/>

  <script type="text/javascript" async defer data-pin-color="red" data-pin-height="32" data-pin-shape="round" data-pin-hover="true" src="//assets.pinterest.com/js/pinit.js"></script>
  <%= yield :head %>
</head>
<body>

<div id="top">

  <div id="cabecalho">
    <div class="redes_sociais">
      <%= link_to (image_tag 'icon-facebook.png', class: 'icon-facebook'), "https://www.facebook.com/bloglalulins", target: '_blank', title: 'Facebook' %>
      <%= link_to (image_tag 'icon-twitter.png', class: 'icon-twitter'), "http://twitter.com/lalu_lins", target: '_blank', title: 'Twitter' %>
      <%= link_to (image_tag 'icon-instagram.png', class: 'icon-instagram'), "http://instagram.com/lalu_lins", target: '_blank', title: 'Instagram' %>
      <%= link_to (image_tag 'icon-pinterest.png', class: 'icon-pinterest'), "http://www.pinterest.com/lalulins/", target: '_blank', title: 'Pinterest' %>
      <%= link_to (image_tag 'icon-bloglovin.png', class: 'icon-bloglovin'), "https://www.bloglovin.com/blogs/lalu-lins-13906443", target: '_blank', title: "Bloglovin'" %>
      <%= link_to (image_tag 'icon-rss.png', class: 'icon-rss'), feed_url(format: "rss"), target: '_blank', title: 'RSS Feed' %>
    </div>
    <div id="busca">
      <%= form_tag busca_path, method: :get, class: 'navbar-form pull-right' do %>
          <%= text_field_tag 'search', params[:search] || 'Buscar', id: 'busca_input' %>
          <button id="busca_button" type="submit" class="btn btn-small"><%= image_tag 'search.png' %></button>
      <% end %>
    </div>
    <div id="logomarca"><%= link_to image_tag('logo2.png'), 'http://lalulins.com.br/' %></div>
  </div>

  <div id="menu" class="navbar">
    <div class="navbar-inner">
      <div class="container">

        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse">
          <!-- .nav, .navbar-search, .navbar-form, etc -->
          <ul class="nav">
            <% Category.all.each do |category| %>
                <li><%= link_to category.name, categoria_path(category.id), {id: "menu_categoria_" + category.id.to_s} %></li>
            <% end %>
          </ul>
        </div>

      </div>
    </div>
  </div>
</div>

<div id="conteudo">

  <div id="carrousel">
    <div id="allinone_carousel_charming">
      <div class="myloader"></div>
      <!-- CONTENT -->
      <ul class="allinone_carousel_list">
        <% @hot_posts.each do |hot_post| %>
            <li data-link="<%= post_path(hot_post.id) %>" data-target="_self">
              <div>
                <%= image_tag hot_post.cropped_main_image(:hotpost) %>
                <div class='carousel_subtitle'><span><%= hot_post.title.downcase %></span></div>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
  </div>

  <%= yield %>
</div>

<div id="rodape">
  <div class="content">

    <ul class="redes_sociais">
      <li>
        <%= link_to (image_tag 'icon-facebook.png', class: 'icon-facebook'), "https://www.facebook.com/bloglalulins", target: '_blank' %>
        <span><%= link_to 'fb.com/bloglalulins', "https://www.facebook.com/bloglalulins", target: '_blank' %></span>
      </li>
      <li>
        <%= link_to (image_tag 'icon-twitter.png', class: 'icon-twitter'), "http://twitter.com/lalu_lins", target: '_blank' %>
        <span><%= link_to '@lalu_lins', "http://twitter.com/lalu_lins", target: '_blank' %></span>
      </li>
      <li>
        <%= link_to (image_tag 'icon-instagram.png', class: 'icon-instagram'), "http://instagram.com/lalu_lins", target: '_blank' %>
        <span><%= link_to 'lalu_lins', "http://instagram.com/lalu_lins", target: '_blank' %></span>
      </li>
      <li>
        <%= link_to (image_tag 'icon-pinterest.png', class: 'icon-pinterest'), "http://www.pinterest.com/lalulins/", target: '_blank' %>
        <span><%= link_to 'lalulins', "http://www.pinterest.com/lalulins/", target: '_blank' %></span>
      </li>
      <li>
        <%= link_to (image_tag 'icon-bloglovin.png', class: 'icon-bloglovin'), "http://www.bloglovin.com/blogs/lalu-lins-4280237", target: '_blank' %>
        <span><%= link_to "lalu on bloglovin'", "https://www.bloglovin.com/blogs/lalu-lins-13906443", target: '_blank' %></span>
      </li>
      <li>
        <%= link_to (image_tag 'icon-rss.png', class: 'icon-rss'), feed_url(format: "rss"), target: '_blank' %>
        <span><%= link_to "rss feed", feed_url(format: "rss"), target: '_blank' %></span>
      </li>
    </ul>

    <ul class="site_info">
      <li><%= link_to 'Sobre', sobre_path %></li>
      <li><%= link_to 'Contato', contato_path %></li>
      <li><%= link_to 'Anuncie', anuncie_path %></li>
    </ul>

    <ul class="catgorias">
      <% Category.all.each do |category| %>
          <li><%= link_to category.name, categoria_path(category.id), {id: "rodape_categoria_" + category.id.to_s} %></li>
      <% end %>
    </ul>


    <p class="creditos">&copy; 2014 - Lalu Lins</p>

    <p class="creditos bitmine">
      Desenvolvido por <br/>
      <%= link_to(image_tag('logo-bitmine-100.png'), 'http://www.bitmine.com.br/', target: '_blank') %>
    </p>
  </div>
</div>

<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-48104772-1', 'lalulins.com.br');
    ga('send', 'pageview');

</script>

</body>
</html>